staging:iio:iio-trig-bfin-timer: Fix compile error
This patch fixes the following compile errors for the iio-trig-bfin-timer
driver:
	drivers/staging/iio/trigger/iio-trig-bfin-timer.c: In function ‘iio_bfin_tmr_frequency_store’:
	drivers/staging/iio/trigger/iio-trig-bfin-timer.c:121: error: invalid storage class for function ‘iio_bfin_tmr_frequency_show’
	drivers/staging/iio/trigger/iio-trig-bfin-timer.c:118: warning: ISO C90 forbids mixed declarations and code
	drivers/staging/iio/trigger/iio-trig-bfin-timer.c:135: error: initializer element is not constant
	...

The issue was introduced in commit 4c858428 ("staging: iio: replace
strict_strto*() with kstrto*()") by leaving an excess opening bracket.

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
Signed-off-by: Jonathan Cameron <jic23@kernel.org>