ARM: OMAP2+: Fix fallout from localtimer divorce and SMP=n
A recent patch 9c87331 (ARM: OMAP2+: Divorce from local timer API,
2013-03-04) broke the omap build when SMP=n because the TWD functions
are only compiled on SMP=y builds. Stub out the TWD calls when the TWD
isn't built in to to keep everything building.

arch/arm/mach-omap2/built-in.o: In function `omap4_local_timer_init':
dss-common.c:(.init.text+0x1d90): undefined reference to `twd_local_timer_register'

Reported-by: Russell King <rmk+kernel@arm.linux.org.uk>
Acked-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Olof Johansson <olof@lixom.net>