staging: make board support depend on OF_IRQ and CLKDEV_LOOKUP
Building allmodconfig for arch/cris currently fails with:

drivers/built-in.o: In function `board_staging_register_clock':
drivers/staging/board/board.c:131: undefined reference to `clk_add_alias'
make: *** [vmlinux] Error 1

The clk_add_alias lives in drivers/clk/clkdev.c and that file
is only compiled for CONFIG_CLKDEV_LOOKUP, so it would seem
we need to add a dependency on that.

Geert also reported seeing this in his build coverage:

  There seems to be another missing dependency on OF_IRQ:

  drivers/built-in.o: In function `board_staging_gic_fixup_resources':
  (.init.text+0x21c2): undefined reference to `irq_create_of_mapping'

so we might as well fix that at the same time since it is
on the same line.

Cc: Magnus Damm <damm+renesas@opensource.se>
Cc: Simon Horman <horms+renesas@verge.net.au>
Cc: Geert Uytterhoeven <geert+renesas@glider.be>
Acked-by: Geert Uytterhoeven <geert+renesas@glider.be>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Chen Gang <gang.chen.5i5j@gmail.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>