Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 8eda4f09bbff4560473a0e049ba8ac950900f33c.

Commit 8eda4f09bbff results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 8eda4f09bbff ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>