Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 60ad52decc52df93f744f39d28862ca5fb1abe98, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer