ANDROID: ppp: pppolac: pppopns: Add (u8 *) cast to skb_push()
Upstream commit be057db68feb ("networking: make skb_push &
__skb_push return void pointers"), made skb_push() return
void *. Add a (u8 *) cast where the unsigned char pointer
is used directly, otherwise we run into following build error:

  CC [M]  drivers/net/ppp/pppolac.o
  CC [M]  drivers/net/ppp/pppopns.o
drivers/net/ppp/pppopns.c: In function 'pppopns_recv_core':
drivers/net/ppp/pppopns.c:115:19: warning: dereferencing 'void *' pointer
   skb_push(skb, 1)[0] = 0;
                   ^
drivers/net/ppp/pppopns.c:115:3: error: invalid use of void expression
   skb_push(skb, 1)[0] = 0;
   ^
drivers/net/ppp/pppolac.c: In function 'pppolac_recv_core':
drivers/net/ppp/pppolac.c:133:19: warning: dereferencing 'void *' pointer
   skb_push(skb, 1)[0] = 0;
                   ^
drivers/net/ppp/pppolac.c:133:3: error: invalid use of void expression
   skb_push(skb, 1)[0] = 0;
   ^
scripts/Makefile.build:308: recipe for target 'drivers/net/ppp/pppopns.o' failed
make[3]: *** [drivers/net/ppp/pppopns.o] Error 1
make[3]: *** Waiting for unfinished jobs....
scripts/Makefile.build:308: recipe for target 'drivers/net/ppp/pppolac.o' failed
make[3]: *** [drivers/net/ppp/pppolac.o] Error 1
scripts/Makefile.build:561: recipe for target 'drivers/net/ppp' failed
make[2]: *** [drivers/net/ppp] Error 2

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>